apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/blog-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/uploads

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
spec:
  storageClassName: fast-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/cache-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
spec:
  storageClassName: fast-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/redis-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
spec:
  storageClassName: fast-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/redis-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-2
spec:
  storageClassName: fast-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/redis-2